START RequestId: XXXX Version: $LATEST
{"m": "aws.lambda.enhanced.invocations", "v": 1, "e": XXXX, "t": ["region:sa-east-1", "account_id:XXXX", "functionname:python-integration-tests-XXXX-sync-metrics_python36", "resource:python-integration-tests-XXXX-sync-metrics_python36", "cold_start:true", "memorysize:1024", "runtime:python3.6", "datadog_lambda:vXX", "dd_lambda_layer:datadog-python36_X.X.X"]}
{"m": "aws.lambda.enhanced.errors", "v": 1, "e": XXXX, "t": ["region:sa-east-1", "account_id:XXXX", "functionname:python-integration-tests-XXXX-sync-metrics_python36", "resource:python-integration-tests-XXXX-sync-metrics_python36", "cold_start:true", "memorysize:1024", "runtime:python3.6", "datadog_lambda:vXX", "dd_lambda_layer:datadog-python36_X.X.X"]}
HTTP POST https://api.datadoghq.com/api/v1/distribution_points?api_key=XXXX Headers: ["Accept-Encoding:gzip, deflate", "Accept:*/*", "Connection:keep-alive", "Content-Encoding:deflate", "Content-Length:XXXX", "Content-Type:application/json", "User-Agent:datadogpy/0.39.0 (python 3.6.13; os linux; arch x86_64)", "x-datadog-parent-id:XXXX", "x-datadog-sampling-priority:1", "x-datadog-trace-id:XXXX"] Data: {"series": [{"metric": "hello.dog", "points": [[XXXX, [1.0]]], "type": "distribution", "host": null, "device": null, "tags": ["team:serverless", "role:hello", "dd_lambda_layer:datadog-python36_X.X.X"], "interval": 10}, {"metric": "tests.integration.count", "points": [[XXXX, [21.0]]], "type": "distribution", "host": null, "device": null, "tags": ["test:integration", "role:hello", "dd_lambda_layer:datadog-python36_X.X.X"], "interval": 10}]}
{"traces": [[{"trace_id": "XXXX", "parent_id": "XXXX", "span_id": "XXXX", "service": "aws.lambda", "resource": "python-integration-tests-XXXX-sync-metrics_python36", "name": "aws.lambda", "error": 1, "start": XXXX, "duration": XXXX, "meta": {"_dd.origin": "lambda", "runtime-id": "XXXX", "cold_start": "true", "function_arn": "arn:aws:lambda:sa-east-1:601427279990:function:python-integration-tests-XXXX-sync-metrics_python36", "function_version": "$LATEST", "request_id": "XXXX", "resource_names": "python-integration-tests-XXXX-sync-metrics_python36", "datadog_lambda": "X.X.X", "dd_trace": "X.X.X", "function_trigger.event_source": "api-gateway", "function_trigger.event_source_arn": "arn:aws:apigateway:sa-east-1::/restapis/wt6mne2s9k/stages/test", "http.method": "GET", "error.msg": "name 'requests' is not defined", "error.type": "builtins.NameError", "error.stack": "Traceback (most recent call last):\n  File \"/opt/python/lib/python3.6/site-packages/datadog_lambda/wrapper.py\", line 124, in __call__\n    self.response = self.func(event, context, **kwargs)\n  File \"/var/task/handle.py\", line 27, in handle\n    requests.get(\"https://httpstat.us/200/\")\nNameError: name 'requests' is not defined\n", "http.status_code": "502"}, "metrics": {"_dd.agent_psr": 1.0, "system.pid": XXXX, "_sampling_priority_v1": 1}, "type": "serverless"}, {"trace_id": "XXXX", "parent_id": "XXXX", "span_id": "XXXX", "service": "aws.lambda", "resource": "requests.request", "name": "requests.request", "error": 0, "start": XXXX, "duration": XXXX, "meta": {"_dd.origin": "lambda", "http.method": "POST", "http.url": "https://api.datadoghq.com/api/v1/distribution_points", "http.status_code": "202"}, "metrics": {"_dd.measured": 1}, "type": "http"}]]}
name 'requests' is not defined: NameError
Traceback (most recent call last):
  File "/opt/python/lib/python3.6/site-packages/datadog_lambda/wrapper.py", line 124, in __call__
    self.response = self.func(event, context, **kwargs)
  File "/var/task/handle.py", line 27, in handle
    requests.get("https://httpstat.us/200/")
NameError: name 'requests' is not defined
END RequestId: XXXX
REPORT RequestId: XXXX	Duration: XXXX ms	Billed Duration: XXXX ms	Memory Size: 1024 MB	Max Memory Used: XXXX MB	Init Duration: XXXX ms	
START RequestId: XXXX Version: $LATEST
{"m": "aws.lambda.enhanced.invocations", "v": 1, "e": XXXX, "t": ["region:sa-east-1", "account_id:XXXX", "functionname:python-integration-tests-XXXX-sync-metrics_python36", "resource:python-integration-tests-XXXX-sync-metrics_python36", "cold_start:false", "memorysize:1024", "runtime:python3.6", "datadog_lambda:vXX", "dd_lambda_layer:datadog-python36_X.X.X"]}
{"m": "aws.lambda.enhanced.errors", "v": 1, "e": XXXX, "t": ["region:sa-east-1", "account_id:XXXX", "functionname:python-integration-tests-XXXX-sync-metrics_python36", "resource:python-integration-tests-XXXX-sync-metrics_python36", "cold_start:false", "memorysize:1024", "runtime:python3.6", "datadog_lambda:vXX", "dd_lambda_layer:datadog-python36_X.X.X"]}
HTTP POST https://api.datadoghq.com/api/v1/distribution_points?api_key=XXXX Headers: ["Accept-Encoding:gzip, deflate", "Accept:*/*", "Connection:keep-alive", "Content-Encoding:deflate", "Content-Length:XXXX", "Content-Type:application/json", "User-Agent:datadogpy/0.39.0 (python 3.6.13; os linux; arch x86_64)", "x-datadog-parent-id:XXXX", "x-datadog-sampling-priority:1", "x-datadog-trace-id:XXXX"] Data: {"series": [{"metric": "hello.dog", "points": [[XXXX, [1.0]]], "type": "distribution", "host": null, "device": null, "tags": ["team:serverless", "role:hello", "dd_lambda_layer:datadog-python36_X.X.X"], "interval": 10}, {"metric": "tests.integration.count", "points": [[XXXX, [21.0]]], "type": "distribution", "host": null, "device": null, "tags": ["test:integration", "role:hello", "dd_lambda_layer:datadog-python36_X.X.X"], "interval": 10}]}
{"traces": [[{"trace_id": "XXXX", "parent_id": "XXXX", "span_id": "XXXX", "service": "aws.lambda", "resource": "python-integration-tests-XXXX-sync-metrics_python36", "name": "aws.lambda", "error": 1, "start": XXXX, "duration": XXXX, "meta": {"_dd.origin": "lambda", "runtime-id": "XXXX", "cold_start": "false", "function_arn": "arn:aws:lambda:sa-east-1:601427279990:function:python-integration-tests-XXXX-sync-metrics_python36", "function_version": "$LATEST", "request_id": "XXXX", "resource_names": "python-integration-tests-XXXX-sync-metrics_python36", "datadog_lambda": "X.X.X", "dd_trace": "X.X.X", "function_trigger.event_source": "sns", "function_trigger.event_source_arn": "arn:aws:sns:us-east-2:123456789012:sns-lambda", "error.msg": "name 'requests' is not defined", "error.type": "builtins.NameError", "error.stack": "Traceback (most recent call last):\n  File \"/opt/python/lib/python3.6/site-packages/datadog_lambda/wrapper.py\", line 124, in __call__\n    self.response = self.func(event, context, **kwargs)\n  File \"/var/task/handle.py\", line 27, in handle\n    requests.get(\"https://httpstat.us/200/\")\nNameError: name 'requests' is not defined\n"}, "metrics": {"_dd.agent_psr": 1.0, "system.pid": XXXX, "_sampling_priority_v1": 1}, "type": "serverless"}, {"trace_id": "XXXX", "parent_id": "XXXX", "span_id": "XXXX", "service": "aws.lambda", "resource": "requests.request", "name": "requests.request", "error": 0, "start": XXXX, "duration": XXXX, "meta": {"_dd.origin": "lambda", "http.method": "POST", "http.url": "https://api.datadoghq.com/api/v1/distribution_points", "http.status_code": "202"}, "metrics": {"_dd.measured": 1}, "type": "http"}]]}
name 'requests' is not defined: NameError
Traceback (most recent call last):
  File "/opt/python/lib/python3.6/site-packages/datadog_lambda/wrapper.py", line 124, in __call__
    self.response = self.func(event, context, **kwargs)
  File "/var/task/handle.py", line 27, in handle
    requests.get("https://httpstat.us/200/")
NameError: name 'requests' is not defined
END RequestId: XXXX
REPORT RequestId: XXXX	Duration: XXXX ms	Billed Duration: XXXX ms	Memory Size: 1024 MB	Max Memory Used: XXXX MB	
START RequestId: XXXX Version: $LATEST
{"m": "aws.lambda.enhanced.invocations", "v": 1, "e": XXXX, "t": ["region:sa-east-1", "account_id:XXXX", "functionname:python-integration-tests-XXXX-sync-metrics_python36", "resource:python-integration-tests-XXXX-sync-metrics_python36", "cold_start:false", "memorysize:1024", "runtime:python3.6", "datadog_lambda:vXX", "dd_lambda_layer:datadog-python36_X.X.X"]}
{"m": "aws.lambda.enhanced.errors", "v": 1, "e": XXXX, "t": ["region:sa-east-1", "account_id:XXXX", "functionname:python-integration-tests-XXXX-sync-metrics_python36", "resource:python-integration-tests-XXXX-sync-metrics_python36", "cold_start:false", "memorysize:1024", "runtime:python3.6", "datadog_lambda:vXX", "dd_lambda_layer:datadog-python36_X.X.X"]}
HTTP POST https://api.datadoghq.com/api/v1/distribution_points?api_key=XXXX Headers: ["Accept-Encoding:gzip, deflate", "Accept:*/*", "Connection:keep-alive", "Content-Encoding:deflate", "Content-Length:XXXX", "Content-Type:application/json", "User-Agent:datadogpy/0.39.0 (python 3.6.13; os linux; arch x86_64)", "x-datadog-parent-id:XXXX", "x-datadog-sampling-priority:1", "x-datadog-trace-id:XXXX"] Data: {"series": [{"metric": "hello.dog", "points": [[XXXX, [1.0]]], "type": "distribution", "host": null, "device": null, "tags": ["team:serverless", "role:hello", "dd_lambda_layer:datadog-python36_X.X.X"], "interval": 10}, {"metric": "tests.integration.count", "points": [[XXXX, [21.0]]], "type": "distribution", "host": null, "device": null, "tags": ["test:integration", "role:hello", "dd_lambda_layer:datadog-python36_X.X.X"], "interval": 10}]}
{"traces": [[{"trace_id": "XXXX", "parent_id": "XXXX", "span_id": "XXXX", "service": "aws.lambda", "resource": "python-integration-tests-XXXX-sync-metrics_python36", "name": "aws.lambda", "error": 1, "start": XXXX, "duration": XXXX, "meta": {"_dd.origin": "lambda", "runtime-id": "XXXX", "cold_start": "false", "function_arn": "arn:aws:lambda:sa-east-1:601427279990:function:python-integration-tests-XXXX-sync-metrics_python36", "function_version": "$LATEST", "request_id": "XXXX", "resource_names": "python-integration-tests-XXXX-sync-metrics_python36", "datadog_lambda": "X.X.X", "dd_trace": "X.X.X", "function_trigger.event_source": "sqs", "function_trigger.event_source_arn": "arn:aws:sqs:us-east-2:123456789012:my-queue", "error.msg": "name 'requests' is not defined", "error.type": "builtins.NameError", "error.stack": "Traceback (most recent call last):\n  File \"/opt/python/lib/python3.6/site-packages/datadog_lambda/wrapper.py\", line 124, in __call__\n    self.response = self.func(event, context, **kwargs)\n  File \"/var/task/handle.py\", line 27, in handle\n    requests.get(\"https://httpstat.us/200/\")\nNameError: name 'requests' is not defined\n"}, "metrics": {"system.pid": XXXX, "_sampling_priority_v1": 1}, "type": "serverless"}, {"trace_id": "XXXX", "parent_id": "XXXX", "span_id": "XXXX", "service": "aws.lambda", "resource": "requests.request", "name": "requests.request", "error": 0, "start": XXXX, "duration": XXXX, "meta": {"_dd.origin": "lambda", "http.method": "POST", "http.url": "https://api.datadoghq.com/api/v1/distribution_points", "http.status_code": "202"}, "metrics": {"_dd.measured": 1}, "type": "http"}]]}
name 'requests' is not defined: NameError
Traceback (most recent call last):
  File "/opt/python/lib/python3.6/site-packages/datadog_lambda/wrapper.py", line 124, in __call__
    self.response = self.func(event, context, **kwargs)
  File "/var/task/handle.py", line 27, in handle
    requests.get("https://httpstat.us/200/")
NameError: name 'requests' is not defined
END RequestId: XXXX
REPORT RequestId: XXXX	Duration: XXXX ms	Billed Duration: XXXX ms	Memory Size: 1024 MB	Max Memory Used: XXXX MB	
